# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('initial_post_date', models.DateField(auto_now_add=True)),
                ('last_edited_date', models.DateField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1)),
                ('initial_post_date', models.DateField(auto_now_add=True)),
                ('last_edited_date', models.DateField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyDebate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('status', models.CharField(choices=[('N', 'Not started'), ('O', 'Open'), ('V', 'In voting'), ('C', 'Complete')], default='N', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, unique=True)),
                ('current_role', models.CharField(choices=[('S', 'Spectator'), ('D', 'Debater'), ('A', 'Administrator')], default='S', max_length=1)),
                ('admin_capable', models.BooleanField(default='N')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DailyDebate'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Argument'),
        ),
        migrations.AddField(
            model_name='argument',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='argument',
            name='parent_debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DailyDebate'),
        ),
    ]
