# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='isReported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='argument',
            name='reasonForBeingReported',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
