# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171127_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
