# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 23:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20171127_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('understand_topic', models.IntegerField()),
                ('respectful', models.IntegerField()),
                ('logical', models.IntegerField()),
                ('accurate_info', models.IntegerField()),
                ('convincing', models.IntegerField()),
                ('grader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Argument')),
            ],
        ),
    ]
