# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-03 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='total',
            field=models.IntegerField(default=22),
            preserve_default=False,
        ),
    ]
